AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Third party API functionality for Wild Rydes

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        SECRET_NAME: secure-serverless-db-secret # name of the RDS credentials in secrets manager

Parameters:
  InitResourceStack:
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: Secure-Serverless

Resources:
  CognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-users'

  PartnerDDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ClientID
        Type: String
      TableName: !Sub '${AWS::StackName}-WildRydePartners'
      

#Custom Authorizer Function
  CustomAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authorizer/
      Runtime: nodejs20.x
      Handler: index.handler
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - "dynamodb:*"
            Resource: "*"
      Environment:
        Variables:
          USER_POOL_ID: !Ref CognitoUserPool
          PARTNER_DDB_TABLE: !Ref PartnerDDBTable
          

#API Gateway AuthorizerRole 
  ApiGatewayAuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: "InvokeAuthorizerFunction"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                Resource:
                  Fn::Sub: ${CustomAuthorizerFunction.Arn}

  ManagePartnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: managePartners.lambda_handler
      Runtime: nodejs20.x
      Policies:
        - VPCAccessPolicy: {}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "cognito-idp:*"
              Resource: "*"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "dynamodb:*"
              Resource: "*"
#        - Version: '2012-10-17'
#          Statement:
#            - Effect: Allow
#              Action:
#                - "secretsmanager:GetSecretValue"
#              Resource: "*"
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${InitResourceStack}-LambdaSecurityGroup"
        SubnetIds:
          - Fn::ImportValue: !Sub "${InitResourceStack}-PrivateSubnet1"
          - Fn::ImportValue: !Sub "${InitResourceStack}-PrivateSubnet2"
      Events:
        CreatePartner:
          Type: Api
          Properties:
            Path: /partners
            Method: post
            RestApiId:
              Ref: UnicornApi
      Environment:
        Variables:
          USER_POOL_ID: !Ref CognitoUserPool
          PARTNER_DDB_TABLE: !Ref PartnerDDBTable


  CustomizeUnicornFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: customizeUnicorn.lambda_handler
      Runtime: nodejs20.x
      Policies:
        - VPCAccessPolicy: {}
#        - Version: '2012-10-17'
#          Statement:
#            - Effect: Allow
#              Action:
#                - "verifiedpermissions:IsAuthorized"
#                - "verifiedpermissions:CreatePolicy"
#                - "verifiedpermissions:ListPolicies"
#                - "verifiedpermissions:DeletePolicy"
#              Resource: "*"
#        - Version: '2012-10-17'
#          Statement:
#            - Effect: Allow
#              Action:
#                - "secretsmanager:GetSecretValue"
#              Resource: "*"
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${InitResourceStack}-LambdaSecurityGroup"
        SubnetIds:
          - Fn::ImportValue: !Sub "${InitResourceStack}-PrivateSubnet1"
          - Fn::ImportValue: !Sub "${InitResourceStack}-PrivateSubnet2"
      Events:
        ListCustomizations:
          Type: Api
          Properties:
            Path: /customizations
            Method: get
            RestApiId:
              Ref: UnicornApi
        CreateCustomizations:
          Type: Api
          Properties:
            Path: /customizations
            Method: post
            RestApiId:
              Ref: UnicornApi
        GetCustomization:
          Type: Api
          Properties:
            Path: /customizations/{id}
            Method: get
            RestApiId:
              Ref: UnicornApi
        DeleteCustomization:
          Type: Api
          Properties:
            Path: /customizations/{id}
            Method: delete
            RestApiId:
              Ref: UnicornApi

  UnicornPartsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: unicornParts.lambda_handler
      Runtime: nodejs20.x
      Policies:
        - VPCAccessPolicy: {}
#        - Version: '2012-10-17'
#          Statement:
#            - Effect: Allow
#              Action:
#                - "secretsmanager:GetSecretValue"
#              Resource: "*"
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${InitResourceStack}-LambdaSecurityGroup"
        SubnetIds:
          - Fn::ImportValue: !Sub "${InitResourceStack}-PrivateSubnet1"
          - Fn::ImportValue: !Sub "${InitResourceStack}-PrivateSubnet2"
      Events:
        ListSocks:
          Type: Api
          Properties:
            Path: /socks
            Method: get
            RestApiId:
              Ref: UnicornApi
        ListHorns:
          Type: Api
          Properties:
            Path: /horns
            Method: get
            RestApiId:
              Ref: UnicornApi
        ListGlasses:
          Type: Api
          Properties:
            Path: /glasses
            Method: get
            RestApiId:
              Ref: UnicornApi
        ListCapes:
          Type: Api
          Properties:
            Path: /capes
            Method: get
            RestApiId:
              Ref: UnicornApi
  #------Module 9: Lambda IAM modules starts
  CustomUnicornAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "CustomUnicornAnalyticsFunction"
      CodeUri: app/
      Handler: customUnicornAnalytics.lambda_handler
      Runtime: nodejs20.x
      Policies:
        - AdministratorAccess # broad permission. Module9A shows scoped down permission
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${InitResourceStack}-LambdaSecurityGroup"
        SubnetIds:
          - Fn::ImportValue: !Sub "${InitResourceStack}-PrivateSubnet1"
          - Fn::ImportValue: !Sub "${InitResourceStack}-PrivateSubnet2"
      Tags:
        application: customizeUnicorn
      Environment:
        Variables:
          DEMAND_FORECAST_DDB_TABLE: !Ref DemandForecastDDBTable

  DemandForecastScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: "DemandForecastAnalyticsScheduler"
      FlexibleTimeWindow:
        Mode: "OFF"
      ScheduleExpression: "rate(2 minutes)"
      Target:
        Arn: !GetAtt CustomUnicornAnalyticsFunction.Arn
        RoleArn: !GetAtt DemandForecastAnalyticsSchedulerRole.Arn

  DemandForecastAnalyticsSchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CustomUnicornSchedulerLambdaRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt CustomUnicornAnalyticsFunction.Arn
  DemandForecastDDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: RecordTimeStamp
        Type: String
      TableName: !Sub '${AWS::StackName}-CustomizationDemandAnalytics'
  #---- Lambda IAM Module Ends -----

  UnicornApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: "2.0"
        info:
          title:
            Ref: AWS::StackName
          description: Wild Ryde API for describing and managing unicorn customizations
          version: 1.0.0
#Security Definitions
        securityDefinitions:
          CustomAuthorizer:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: custom
            x-amazon-apigateway-authorizer:
              type: token
              authorizerUri:
                Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CustomAuthorizerFunction.Arn}/invocations
              authorizerCredentials:
                Fn::Sub: ${ApiGatewayAuthorizerRole.Arn}
              authorizerResultTtlInSeconds: 60
        paths:
          "/socks":
            get:
              security:
                - CustomAuthorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UnicornPartsFunction.Arn}/invocations
              responses: {}
          "/horns":
            get:
              security:
                - CustomAuthorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UnicornPartsFunction.Arn}/invocations
              responses: {}
          "/glasses":
            get:
              security:
                - CustomAuthorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UnicornPartsFunction.Arn}/invocations
              responses: {}
          "/capes":
            get:
              security:
                - CustomAuthorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UnicornPartsFunction.Arn}/invocations
              responses: {}
          "/customizations":
            get:
              security:
                - CustomAuthorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CustomizeUnicornFunction.Arn}/invocations
              responses: {}
            post:
              security:
                - CustomAuthorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CustomizeUnicornFunction.Arn}/invocations
              responses: {}
          "/customizations/{id}":
            get:
              security:
                - CustomAuthorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CustomizeUnicornFunction.Arn}/invocations
              responses: {}
            delete:
              security:
                - CustomAuthorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CustomizeUnicornFunction.Arn}/invocations
              responses: {}
          "/partners":
            post:
              security:
                - CustomAuthorizer: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManagePartnerFunction.Arn}/invocations
              responses: {}


Outputs:
  ApiURL:
    Description: "API endpoint URL for dev environment"
    Value: !Sub "https://${UnicornApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
